field: bf8f9ed2-2536-4b33-865a-b599e979ae41 # Plant tabel
fieldLayouts:
  c10d467a-5eb1-4243-8645-c72d79d1c586:
    tabs:
      -
        elements:
          -
            fieldUid: 285d3eef-6222-4498-b7d6-2b65971bccf8
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4998a4f9-283c-4851-b305-47828327574c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 42a20019-2e91-46d3-b5f8-380bad575e1f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 505d899e-36b5-47a1-8c00-7880b4ddf0f5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  42a20019-2e91-46d3-b5f8-380bad575e1f:
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: plantMaat
    instructions: ''
    name: Maat
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  285d3eef-6222-4498-b7d6-2b65971bccf8:
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: plantSoort
    instructions: ''
    name: Soort
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  505d899e-36b5-47a1-8c00-7880b4ddf0f5:
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: plantImage
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:112ab554-bad7-4cb7-a22a-4f00cc2c31cc' # imageVolume
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:112ab554-bad7-4cb7-a22a-4f00cc2c31cc' # imageVolume
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:112ab554-bad7-4cb7-a22a-4f00cc2c31cc' # imageVolume
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4998a4f9-283c-4851-b305-47828327574c:
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: plantPotmaat
    instructions: ''
    name: Potmaat
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: plant
name: plant
sortOrder: 1
