defaultPlacement: end
fieldLayouts:
  5a5cf9c4-4716-4823-ac59-b45e2c5b84c8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 358f89a7-6089-4b06-819c-22cb854f3665
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e4e55b6-cc7d-4e29-9dd3-2976f356cac6 # Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef71c5d-78c8-41bb-8096-9e748efdb1ae
            userCondition: null
            warning: null
            width: 100
        name: General
        uid: 7d0e5498-10fc-417f-8744-897af6644ce3
        userCondition: null
handle: plantensoort
name: plantensoort
siteSettings:
  8e3d2eda-3b81-45e3-81c0-9a27b66343c7: # bogaertdirk
    hasUrls: true
    template: null
    uriFormat: 'plantensoort/{slug}'
  ee6d1941-f937-4f7f-8001-726d9d82afb3: # fr
    hasUrls: true
    template: null
    uriFormat: 'plantensoort/{slug}'
structure:
  maxLevels: null
  uid: 76038e7f-bc98-474f-94a8-14902dbf7f0c
