fieldLayouts:
  f5c899c2-2bbf-45b2-914a-ef334ed4614d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7f683960-66d2-49d0-91da-1261dce2bba0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48fb16e6-9ad0-4320-b36e-49a1515f5037
        userCondition: null
fs: imageVolume
handle: imageVolume
name: imageVolume
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
