fieldLayouts:
  77e81dbc-01db-4b2e-9e24-592323b4ff35:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: imageVolume
handle: imageVolume
hasUrls: true
name: imageVolume
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: /uploads
