columnSuffix: null
contentColumnType: text
fieldGroup: ac3c3040-adfa-4e4c-b8a0-06486e5d63c6 # About
handle: aboutTeamDescription
instructions: ''
name: 'Team description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
