columnSuffix: null
contentColumnType: text
fieldGroup: ac3c3040-adfa-4e4c-b8a0-06486e5d63c6 # About
handle: aboutTeamTitle
instructions: ''
name: 'Team title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
