columnSuffix: null
contentColumnType: text
fieldGroup: db880872-957b-45a9-9f5e-4f06493015d9 # Common
handle: commonTitle
instructions: ''
name: Title
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
