columnSuffix: null
contentColumnType: text
fieldGroup: db880872-957b-45a9-9f5e-4f06493015d9 # Common
handle: commonSamenwerkingDescription
instructions: ''
name: 'Samenwerking description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
