columnSuffix: null
contentColumnType: string
handle: commonSamenwerkingDescription
instructions: null
name: 'Samenwerking description'
searchable: true
settings:
  errorMessage: 'Component class ''craft\ckeditor\Field'' belongs to a disabled plugin (CKEditor).'
  expectedType: craft\ckeditor\Field
  settings:
    __assoc__:
      0:
        - availableTransforms
        - '*'
      1:
        - availableVolumes
        - '*'
      2:
        - columnType
        - text
      3:
        - defaultTransform
        - ''
      5:
        - purifierConfig
        - ''
      6:
        - purifyHtml
        - '1'
      7:
        - removeEmptyTags
        - false
      8:
        - removeInlineStyles
        - false
      9:
        - removeNbsp
        - false
      10:
        - showUnpermittedFiles
        - ''
      11:
        - showUnpermittedVolumes
        - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
