contentColumnType: text
fieldGroup: db880872-957b-45a9-9f5e-4f06493015d9 # Common
handle: commonSamenwerkingDescription
instructions: ''
name: 'Samenwerking description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
