columnSuffix: null
contentColumnType: text
fieldGroup: 66e900e2-e7cf-47e4-a7d4-f8362307c4c5 # Globals
handle: globalContactDescription
instructions: ''
name: 'Contact description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
