columnSuffix: null
contentColumnType: string
handle: globalContactMail
instructions: null
name: 'Contact mail'
searchable: true
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Email
