contentColumnType: text
fieldGroup: 66e900e2-e7cf-47e4-a7d4-f8362307c4c5 # Globals
handle: globalContactGsm
instructions: ''
name: 'Contact gsm Dirk'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
