columnSuffix: null
contentColumnType: text
handle: globalContactGsmAnn
instructions: null
name: 'Contact gsm ann'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
