columnSuffix: null
contentColumnType: text
fieldGroup: b1c99512-2cc4-4b8e-a95f-d96b1f4aa7ab # Home
handle: homeSpotlightTitle
instructions: ''
name: 'Home spotlight title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
