columnSuffix: null
contentColumnType: text
fieldGroup: 33570d82-e546-4702-939f-eb5ddfb333f2 # Nav
handle: navIntroduction
instructions: ''
name: 'Navigation introduction'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  defaultTransform: ''
  initJs: null
  purifierConfig: ''
  purifyHtml: '1'
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
