columnSuffix: null
contentColumnType: text
fieldGroup: 33570d82-e546-4702-939f-eb5ddfb333f2 # Nav
handle: navTitle
instructions: ''
name: 'Navigation Titel'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
