columnSuffix: null
contentColumnType: string
handle: plantTable
instructions: null
name: 'Plant tabel'
searchable: true
settings:
  entryTypes:
    -
      uid: a04ec161-89d3-4a1d-8c54-eec5076c9d1b
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
