columnSuffix: null
handle: plantPotmaat
instructions: null
name: 'Plant tabel - plant - Potmaat'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
