columnSuffix: null
contentColumnType: string
fieldGroup: 4476a42f-adcd-4434-af71-726edade8d78 # Plant
handle: plantTable
instructions: ''
name: 'Plant tabel'
searchable: true
settings:
  contentTable: '{{%matrixcontent_planttable}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
