dateModified: 1699003729
email:
  fromEmail: collin@littlemissrobot.com
  fromName: bogaertdirk
  template: null
  transportSettings:
    password: mailer!!!
    timeout: '10'
    username: bogaertdirkmailer@gmail.com
  transportType: craft\mail\transportadapters\Gmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0c58095e-dc53-4cc1-bc3a-afed77de981b: 'About photo 2' # About photo 2
    0e7fe416-9d2f-49ba-b787-71d197ce63b8: 'Team title' # Team title
    1c8df03f-74fd-444b-a5bf-56ef9259b053: 'Contact cta label' # Contact cta label
    4f141aa0-39f7-44f5-b512-87ca295158e9: 'Contact gsm Dirk' # Contact gsm Dirk
    5b8bf9f9-1792-4d72-9915-ff0b0da27122: 'Contact description' # Contact description
    6feaa6c6-cbc4-4792-8952-95e65d591552: 'Contact titel gegevens' # Contact titel gegevens
    7a9e020d-adca-4048-afc9-5094dc7726b9: 'Detail cta' # Detail cta
    9e4e55b6-cc7d-4e29-9dd3-2976f356cac6: Introduction # Introduction
    35c51972-f750-46bd-8331-9d578096d49e: 'Link cta' # Link cta
    44fdd2fb-939a-4c5a-9867-6bf7a15674ab: 'Global other variants' # Global other variants
    48fb4ee4-713e-4d5c-a79c-1ae69a7c6624: 'Home spotlight title' # Home spotlight title
    51b3aa81-c77a-4a9b-8be9-c126091f80ab: Title # Title
    53e95fa5-8359-49b6-a411-fdf991ad8844: 'Contact title us' # Contact title us
    63ff5245-2ab0-4f3c-b8a7-2ed300e11219: 'Contact straat' # Contact straat
    66e900e2-e7cf-47e4-a7d4-f8362307c4c5: Globals # Globals
    089b433e-278d-4f41-8899-d9c6a0803b27: 'Detail interested' # Detail interested
    95ab273c-55fa-4c0d-8fe4-1c7cbb65de0e: Detail # Detail
    112ab554-bad7-4cb7-a22a-4f00cc2c31cc: imageVolume # imageVolume
    295e67cd-8709-422e-ab9a-b5ee52d61ed8: 'About photo 5' # About photo 5
    473b32ef-0cac-4e8a-a11a-adcc1ab31705: 'About photo 4' # About photo 4
    952b1677-5ade-4e62-b47b-b9936bddcdb6: 'Navigation Titel' # Navigation Titel
    2556a829-b1a9-40e4-b30e-8c6896197b56: Image # Image
    2834c455-1a02-4864-a60d-f96d1bf8d1d2: 'Contact mail' # Contact mail
    3648fc6c-0f04-4d12-ae5f-15dd545c51bb: Seo # Seo
    4476a42f-adcd-4434-af71-726edade8d78: Plant # Plant
    9692be7a-b52c-467c-8a29-4bd16fd03f51: 'Navigation introduction' # Navigation introduction
    33570d82-e546-4702-939f-eb5ddfb333f2: Nav # Nav
    177033ee-3b58-40af-9843-544791e3eb28: 'About photo 3' # About photo 3
    6993150b-68b3-43d0-bfc0-c45fbfd10acf: 'Contact phone' # Contact phone
    20577864-05fd-4fea-8d64-6870369c7459: 'Related plants' # Related plants
    73999626-0544-466f-b139-f66fdb06a4ac: Contact # Contact
    a27b376f-9c35-4881-9075-44870c708829: 'Samenwerking description' # Samenwerking description
    ac3c3040-adfa-4e4c-b8a0-06486e5d63c6: About # About
    b1b7b4a1-fdfe-4fb6-9cad-dede76e4b9d8: 'Contact stad' # Contact stad
    b1c99512-2cc4-4b8e-a95f-d96b1f4aa7ab: Home # Home
    b5b893a3-fda3-44ce-8144-153fa6557a69: 'Detail soorten' # Detail soorten
    b14a91d5-7fcc-48ac-9167-815daa8d1767: 'Contact gsm ann' # Contact gsm ann
    bc35ca7f-b5e4-4cad-9bb0-82192041de0f: 'Global variants description' # Global variants description
    bf8f9ed2-2536-4b33-865a-b599e979ae41: 'Plant tabel' # Plant tabel
    d970c6df-bd7c-4ff7-9e92-069dae323455: 'Contact bericht label' # Contact bericht label
    d38063c5-b8d6-4d81-89c0-e8847d81e10e: Plantensoort # Plantensoort
    d50193f6-9657-475c-83f0-046a4e073fcf: 'Team description' # Team description
    d5100871-3a04-4c3f-8cc3-950bd4a780fb: 'Contact mail label' # Contact mail label
    db880872-957b-45a9-9f5e-4f06493015d9: Common # Common
    e9d9d161-74ec-467e-b3e4-da284c293cae: 'Contact name label' # Contact name label
    e29b0f53-3e8d-4c61-84ad-11138b8fbdbf: 'Samenwerking title' # Samenwerking title
    edd52b93-0d86-48b0-ae22-4dac7d77cd9a: 'Detail interested description' # Detail interested description
    fd7a7f9c-e1f4-45c0-9c8c-c2c13b1c2250: 'About photo 1' # About photo 1
    fe658f8b-0a42-4fe8-9a04-13bb7be61b3c: 'Home spotlight description' # Home spotlight description
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: bogaertdirk
  schemaVersion: 3.8.0.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
