fieldLayouts:
  2aa943ad-c0eb-439d-beeb-c8fb1de8e307:
    tabs:
      -
        fields:
          1c8df03f-74fd-444b-a5bf-56ef9259b053: # Contact cta label
            required: false
            sortOrder: 6
          4f141aa0-39f7-44f5-b512-87ca295158e9: # Contact gsm Dirk
            required: false
            sortOrder: 8
          5b8bf9f9-1792-4d72-9915-ff0b0da27122: # Contact description
            required: false
            sortOrder: 2
          6feaa6c6-cbc4-4792-8952-95e65d591552: # Contact titel gegevens
            required: false
            sortOrder: 7
          53e95fa5-8359-49b6-a411-fdf991ad8844: # Contact title us
            required: false
            sortOrder: 1
          63ff5245-2ab0-4f3c-b8a7-2ed300e11219: # Contact straat
            required: false
            sortOrder: 13
          2834c455-1a02-4864-a60d-f96d1bf8d1d2: # Contact mail
            required: false
            sortOrder: 10
          6993150b-68b3-43d0-bfc0-c45fbfd10acf: # Contact phone
            required: false
            sortOrder: 11
          b1b7b4a1-fdfe-4fb6-9cad-dede76e4b9d8: # Contact stad
            required: false
            sortOrder: 12
          b14a91d5-7fcc-48ac-9167-815daa8d1767: # Contact gsm ann
            required: false
            sortOrder: 9
          d970c6df-bd7c-4ff7-9e92-069dae323455: # Contact bericht label
            required: false
            sortOrder: 5
          d5100871-3a04-4c3f-8cc3-950bd4a780fb: # Contact mail label
            required: false
            sortOrder: 4
          e9d9d161-74ec-467e-b3e4-da284c293cae: # Contact name label
            required: false
            sortOrder: 3
        name: Contact
        sortOrder: 1
handle: globalContact
name: Contact
sortOrder: 1
