defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 22de7467-4229-462d-8bfb-53775fbc87be # Catalogus
handle: pageCatalogus
maxAuthors: 1
name: Catalogus
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  8e3d2eda-3b81-45e3-81c0-9a27b66343c7: # bogaertdirk
    enabledByDefault: true
    hasUrls: true
    template: /pages/catalogus
    uriFormat: catalogus
  ee6d1941-f937-4f7f-8001-726d9d82afb3: # fr
    enabledByDefault: true
    hasUrls: true
    template: /pages/catalogus
    uriFormat: catalogus
type: single
