defaultPlacement: end
enableVersioning: true
handle: planten
name: planten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  8e3d2eda-3b81-45e3-81c0-9a27b66343c7:
    enabledByDefault: true
    hasUrls: true
    template: /pages/detail
    uriFormat: 'planten/{slug}'
  ee6d1941-f937-4f7f-8001-726d9d82afb3:
    enabledByDefault: true
    hasUrls: true
    template: /pages/detail
    uriFormat: 'planten/{slug}'
structure:
  maxLevels: null
  uid: 33dc62c2-1e11-4bf3-8bdb-a491d355c1b7
type: structure
